# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NextMatchReborn' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NextMatchReborn

  target 'NextMatchRebornTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# Auth0 Lock

pod 'Lock', '~> 1.26'
pod 'Lock/TouchID'
pod 'Lock/SMS'
pod 'Lock/Email'
pod 'Firebase/Auth'
pod 'Firebase'
pod "youtube-ios-player-helper", "~> 0.1.4"